name: sewers
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - geopandas
  - cartopy>=0.21
  - notebook
  - rasterio
  - pyepsg
  - folium
  - pyproj
  - tqdm
  - pandas
  - geopy
  - pyogrio
  - openpyxl
